server:
  port: 9001
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

spring:
  main:
    web-application-type: servlet

  profiles:
    active: 

  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      path: '/h2-console'
      enabled: true

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
